<!-- Vendor JS -->
<script src="{{ asset('theme/client/assets/js/vendor/modernizr-3.11.2.min.js') }}"></script>
<script src="{{ asset('theme/client/assets/js/vendor/jquery-3.6.0.min.js') }}"></script>
<script src="{{ asset('theme/client/assets/js/vendor/jquery-migrate-3.3.2.min.js') }}"></script>
<script src="{{ asset('theme/client/assets/js/vendor/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('theme/client/assets/js/plugins/swiper-bundle.min.js') }}"></script>
<script src="{{ asset('theme/client/assets/js/plugins/jquery-ui.min.js') }}"></script>
<script src="{{ asset('theme/client/assets/js/plugins/jquery.nice-select.min.js') }}"></script>
<script src="{{ asset('theme/client/assets/js/plugins/countdown.js') }}"></script>
<script src="{{ asset('theme/client/assets/js/plugins/scrollup.js') }}"></script>
<script src="{{ asset('theme/client/assets/js/plugins/jquery.zoom.min.js') }}"></script>
<script src="{{ asset('theme/client/assets/js/plugins/venobox.min.js') }}"></script>
<script src="{{ asset('theme/client/assets/js/plugins/ajax-mail.js') }}"></script>
<script src="{{ asset('theme/client/assets/js/main.js') }}"></script>
